name: build

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint --if-present

      env:
        CI: true
