name: coverage

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: npm ci

    - name: Tests
      run: npm test

    - name: Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

      env:
        CI: true
