# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests

on: 
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci
      name: Install

    - run: npm run lint --if-present
      name: Lint

    - run: npm test
      name: Test

      env:
        CI: true
