name: build

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: npm ci

    - name: Tests
      run: npm test

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: true

      env:
        CI: true
